---
- name: Ensure release directory
  file:
    path: "{{ release_dir }}"
    state: directory
    mode: 0755

- name: Clean release directory
  command: "rm -rf {{ release_dir }}/*"

- name: Ensure release directory
  file:
    path: "{{ release_dir }}"
    state: directory
    mode: 0755